apiVersion: v1
kind: ConfigMap
metadata:
  name: goblncr-config
  namespace: goblncr
data:
  HTTP_ADDRESS: "${HTTP_ADDRESS}"
  HTTP_PORT: "${HTTP_PORT}"
  HTTP_TLS: "${HTTP_TLS}"
  K8S_NAMESPACE: "${K8S_NAMESPACE}"
  K8S_PODS_SELECTOR: "${K8S_PODS_SELECTOR}"
