DIR_ROOT = os.getcwd()
DIR_DEPLOYMENTS = os.path.join(DIR_ROOT, 'deployments', '/')

# configs
k8s_yaml([
    DIR_DEPLOYMENTS + "/k8s/pvc.yaml",
    DIR_DEPLOYMENTS + "/k8s/configmap.yaml",
    DIR_DEPLOYMENTS + "/k8s/deployment.yaml",
    DIR_DEPLOYMENTS + "/k8s/service.yaml",
])

print(DIR_ROOT)

docker_build(
    "express-stats",
    DIR_ROOT + "/app",
    dockerfile=DIR_DEPLOYMENTS + "/docker/Dockerfile",
    build_args={'--no-cache':''}
)


k8s_resource(
  "express-stats",
  port_forwards=8083,
)