apiVersion: v1
kind: ConfigMap
metadata:
  name: goblncr-config
  namespace: goblncr
data:
  BALANCER_ADDRESS: "${BALANCER_ADDRESS}"
  BALANCER_PORT: "${BALANCER_PORT}"
  BALANCER_TLS: "${BALANCER_TLS}"

  TARGET_NAMESPACE: "${TARGET_NAMESPACE}"
  TARGET_SELECTOR: "${TARGET_SELECTOR}"
  TARGET_PORT: "${TARGET_PORT}"
