apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: express-stats
  name: express-stats-pvc
  namespace: goblncr-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
