FROM golang:1.26.5 AS goblncr-dev

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@master
RUN go install github.com/dkorunic/betteralign/cmd/betteralign@v0.14.4

COPY ./build/goblncr-dbg /app/goblncr-dbg
COPY ./config/config.yaml /app/

COPY ./deployments/docker/start-debug.sh /

EXPOSE 8080 2345

ENTRYPOINT ["/start-debug.sh"]
