apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb
  namespace: goblncr-test
data:
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tokenMirEgal
  DOCKER_INFLUXDB_INIT_BUCKET: loadstats
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_ORG: goblncr-test
  DOCKER_INFLUXDB_INIT_PASSWORD: adminpass
  DOCKER_INFLUXDB_INIT_USERNAME: admin
